The ``101-lazy_matrix_mul`` module
=============================

Using ``lazy_matrix_mul``
--------------------

open module
	>>> lazy_matrix_mul = __import__("101-lazy_matrix_mul").lazy_matrix_mul

Documentation:
    >>> len(__import__("101-lazy_matrix_mul").__doc__) > 1
    True
    >>> len(__import__("101-lazy_matrix_mul").lazy_matrix_mul.__doc__) > 1
    True


Check for normal case
    >>> lazy_matrix_mul([[3, 2, 1, 5], [9, 1, 3, 0]], [[2, 9, 0], [1, 3, 5], [2, 4, 7], [8, 1, 5]]) # doctest: 
    array([[50, 42, 42],
           [25, 96, 26]])

Check m_a or m_b not lists?
    >>> lazy_matrix_mul("Matrix", [[1, 2], [3, 4]])
    Traceback (most recent call last):
    ...
    TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U6') dtype('<U6') dtype('<U6')

    >>> lazy_matrix_mul([[1, 2], [3, 4]], "Matix")
    Traceback (most recent call last):
    ...
    TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U5') dtype('<U5') dtype('<U5')

Both are lists of lists?
    >>> lazy_matrix_mul([[1, 2], 3], [[1, 2, 3], [1, 2, 3]])
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.


    >>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2, 3], 4])
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.



Both are not emplty?

    >>> lazy_matrix_mul([], [[1, 2], [3, 4]])
    Traceback (most recent call last):
    ValueError: shapes (0,) and (2,2) not aligned: 0 (dim 0) != 2 (dim 0)

    >>> lazy_matrix_mul([[]], [[1, 2], [3, 4]])
    Traceback (most recent call last):
    ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

    >>> lazy_matrix_mul([[1, 2], [3, 4]], [])
    Traceback (most recent call last):
    ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

    >>> lazy_matrix_mul([[1, 2], [3, 4]], [[]])
    Traceback (most recent call last):
    ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

Correct data types?
    >>> lazy_matrix_mul([[1, "2"], [3, 4]], [[1, 2], [3, 4]])
    Traceback (most recent call last):
    ValueError: data type must provide an itemsize

    >>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], ["3", 4]])
    Traceback (most recent call last):
    ValueError: data type must provide an itemsize


Both have same size rows?
    >>> lazy_matrix_mul([[1, 2], [3, 4, 5]], [[1, 2], [3, 4]])
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.

    >>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4, 5]])
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.


Wrong number of rows and columns?
    >>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    Traceback (most recent call last):
    ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

    >>> lazy_matrix_mul([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2], [3, 4]])
    Traceback (most recent call last):
    ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)
